# Generated by Django 5.2.5 on 2025-10-10 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderstatushistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order Status History",
                "verbose_name_plural": "Order Status Histories",
            },
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLACED", "Order Placed"),
                    ("IN_PROCESS", "Order in Process"),
                    ("DELIVERY_SOON", "Delivery Soon"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PLACED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("PLACED", "Order Placed"),
                    ("IN_PROCESS", "Order in Process"),
                    ("DELIVERY_SOON", "Delivery Soon"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="old_status",
            field=models.CharField(
                choices=[
                    ("PLACED", "Order Placed"),
                    ("IN_PROCESS", "Order in Process"),
                    ("DELIVERY_SOON", "Delivery Soon"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrderTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placed_at", models.DateTimeField(blank=True, null=True)),
                ("in_process_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_soon_at", models.DateTimeField(blank=True, null=True)),
                ("out_for_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_delivery", models.DateTimeField(blank=True, null=True)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("courier_service", models.CharField(blank=True, max_length=100)),
                ("delivery_address", models.TextField(blank=True)),
                ("current_location", models.CharField(blank=True, max_length=200)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Tracking",
                "verbose_name_plural": "Order Tracking",
            },
        ),
    ]
